# -*- coding: utf-8 -*-
"""Linear_Regression_&_OLS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgfNknHbza636uilm3BsdcuRXyPcvCm8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import joblib



data = load_diabetes()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)

print(X.head())
print(X.describe())


print("Dataset shape:", X.shape)
print("Missing values:", X.isnull().sum())

plt.scatter(X["bmi"], y)
plt.xlabel("BMI")
plt.ylabel("Target")
plt.title("BMI vs Target")
plt.show()


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)




scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


X_train_b = np.c_[np.ones((X_train.shape[0], 1)), X_train]


beta = np.linalg.inv(X_train_b.T @ X_train_b) @ X_train_b.T @ y_train

print("OLS coefficients:", beta)


X_test_b = np.c_[np.ones((X_test.shape[0], 1)), X_test]

y_pred_ols = X_test_b @ beta



model = LinearRegression()

model.fit(X_train, y_train)

y_pred_sklearn = model.predict(X_test)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)


mse = mean_squared_error(y_test, y_pred_sklearn)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred_sklearn)

print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)


plt.scatter(y_test, y_pred_sklearn)

plt.xlabel("True values")
plt.ylabel("Predicted values")
plt.title("True vs Predicted")

plt.show()


residuals = y_test - y_pred_sklearn

plt.scatter(y_pred_sklearn, residuals)

plt.axhline(0)

plt.xlabel("Predicted values")
plt.ylabel("Residuals")

plt.title("Residual vs Predicted")

plt.show()




plt.hist(residuals, bins=20)

plt.title("Residual Distribution")

plt.show()

coef_df = pd.DataFrame({
    "Feature": data.feature_names,
    "Coefficient": model.coef_
})

print(coef_df)

joblib.dump(model, "linear_regression_model.joblib")